geometry_msgs/Point wrist_target_left
geometry_msgs/Point wrist_target_right

float32 angle_left_elbow
float32 angle_right_elbow

# Shoulder-to-Elbow vector angles (horizontal = azimuth, vertical = elevation)
float32 sho_elbow_horiz_left
float32 sho_elbow_vert_left
float32 sho_elbow_horiz_right
float32 sho_elbow_vert_right

# Elbow-to-Wrist vector angles (horizontal = azimuth, vertical = elevation)
float32 elbow_wrist_horiz_left
float32 elbow_wrist_vert_left
float32 elbow_wrist_horiz_right
float32 elbow_wrist_vert_right